databases:
  - name: aurelle-db
    plan: free
    databaseName: aurelle
    user: aurelle

services:
  - type: web
    name: aurelle-marketplace
    runtime: node
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: npm ci && npx prisma generate && npx prisma db push && npm run db:seed:if-empty && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aurelle-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: CAPACITOR_SERVER_URL
        sync: false
